---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luofangbing.
--- DateTime: 2022/9/1 9:25 PM
---

local key = KEYS[1]
local max = ARGV[1]

if redis.call('EXISTS', key) == 0 then
    redis.call('SET', key, 1)
    return 1
else
    local incr = redis.call('INCR', key)
    if (tonumber(incr) > tonumber(max)) then
        redis.call('SET', key, 1)
        return 1
    else
        return tonumber(incr)
    end
end