---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luofangbing.
--- DateTime: 2022/7/18 10:29 AM
---

if redis.call("exists",KEYS[1]) == 0 then
    return 1
end

if redis.call('get',KEYS[1]) == ARGV[1] then
    return redis.call('del',KEYS[1])
else
    return 0
end


