
spring:
  application:
    name: web-sample
  redis:
    # 地址
    host: 139.155.247.123
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ym3.1415926...
    # 连接超时时间
    timeout: 10s
server:
  servlet:
    context-path: "/web"
cn:
  me:
    ppx:
      filter:
        auth: true