
spring:
  application:
    name: "@app.name@"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ovo_baas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ym3.1415926...
  redis:
    # 地址
    host: 139.155.247.123
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ym3.1415926...
    # 连接超时时间
    timeout: 10s
server:
  servlet:
    context-path: "/web"
cn:
  me:
    ppx:
      filter:
        auth: true